### ISSUE TITLE
TR2 - TRex crashing game shortly after spawning

### ISSUE THREAD

**Issue by DanzaG** [DanzaG/TR2-Rando#188]
Currently spotted on TR2 Tibetan Foothills.

"The game kept crashing when the trex was spawning in tibetian foothills in the area with two pushable blocks, the trex was replacing one of the snow leopards. it crashed each time i started to try to kill it"

**Comment by lahm86** [comment]
This was followed up on Discord and the crashing was also occurring in Bartoli's Hideout. The level file was checked and all the correct animations are in place for the T-Rex. The level was played/tested and the crashing only seems to happen when using the grenade launcher. Testing was also done in the original Great Wall and it is easy to make the game crash when using the grenade launcher on the T-Rex there.

In terms of workarounds, we could perhaps look at restricting the T-Rex's appearance, but I'm inclined to leave it as-is because this isn't an issue itself with cross-level enemies, more so it's a problem with how the game itself works. Perhaps eventually having a list of the enemies the player wants to include/exclude could be a way forward, or include the T-Rex only in "difficult" mode. 

https://discord.com/channels/871134175963545641/871138634852610128/872036278017875968
https://streamable.com/aguuxj

**Comment by DanzaG** [comment]
As this is a vanilla game issue also, i dont believe we need to make a change. We will just have to warn against it.
